// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hossein1376/kala/internal/ent/comment"
	"github.com/hossein1376/kala/internal/ent/pros"
)

// ProsCreate is the builder for creating a Pros entity.
type ProsCreate struct {
	config
	mutation *ProsMutation
	hooks    []Hook
}

// SetPro sets the "pro" field.
func (pc *ProsCreate) SetPro(s string) *ProsCreate {
	pc.mutation.SetPro(s)
	return pc
}

// SetCommentID sets the "comment" edge to the Comment entity by ID.
func (pc *ProsCreate) SetCommentID(id int) *ProsCreate {
	pc.mutation.SetCommentID(id)
	return pc
}

// SetNillableCommentID sets the "comment" edge to the Comment entity by ID if the given value is not nil.
func (pc *ProsCreate) SetNillableCommentID(id *int) *ProsCreate {
	if id != nil {
		pc = pc.SetCommentID(*id)
	}
	return pc
}

// SetComment sets the "comment" edge to the Comment entity.
func (pc *ProsCreate) SetComment(c *Comment) *ProsCreate {
	return pc.SetCommentID(c.ID)
}

// Mutation returns the ProsMutation object of the builder.
func (pc *ProsCreate) Mutation() *ProsMutation {
	return pc.mutation
}

// Save creates the Pros in the database.
func (pc *ProsCreate) Save(ctx context.Context) (*Pros, error) {
	return withHooks(ctx, pc.sqlSave, pc.mutation, pc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (pc *ProsCreate) SaveX(ctx context.Context) *Pros {
	v, err := pc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pc *ProsCreate) Exec(ctx context.Context) error {
	_, err := pc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pc *ProsCreate) ExecX(ctx context.Context) {
	if err := pc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pc *ProsCreate) check() error {
	if _, ok := pc.mutation.Pro(); !ok {
		return &ValidationError{Name: "pro", err: errors.New(`ent: missing required field "Pros.pro"`)}
	}
	if v, ok := pc.mutation.Pro(); ok {
		if err := pros.ProValidator(v); err != nil {
			return &ValidationError{Name: "pro", err: fmt.Errorf(`ent: validator failed for field "Pros.pro": %w`, err)}
		}
	}
	return nil
}

func (pc *ProsCreate) sqlSave(ctx context.Context) (*Pros, error) {
	if err := pc.check(); err != nil {
		return nil, err
	}
	_node, _spec := pc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	pc.mutation.id = &_node.ID
	pc.mutation.done = true
	return _node, nil
}

func (pc *ProsCreate) createSpec() (*Pros, *sqlgraph.CreateSpec) {
	var (
		_node = &Pros{config: pc.config}
		_spec = sqlgraph.NewCreateSpec(pros.Table, sqlgraph.NewFieldSpec(pros.FieldID, field.TypeInt))
	)
	if value, ok := pc.mutation.Pro(); ok {
		_spec.SetField(pros.FieldPro, field.TypeString, value)
		_node.Pro = value
	}
	if nodes := pc.mutation.CommentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pros.CommentTable,
			Columns: []string{pros.CommentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.comment = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ProsCreateBulk is the builder for creating many Pros entities in bulk.
type ProsCreateBulk struct {
	config
	builders []*ProsCreate
}

// Save creates the Pros entities in the database.
func (pcb *ProsCreateBulk) Save(ctx context.Context) ([]*Pros, error) {
	specs := make([]*sqlgraph.CreateSpec, len(pcb.builders))
	nodes := make([]*Pros, len(pcb.builders))
	mutators := make([]Mutator, len(pcb.builders))
	for i := range pcb.builders {
		func(i int, root context.Context) {
			builder := pcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pcb *ProsCreateBulk) SaveX(ctx context.Context) []*Pros {
	v, err := pcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pcb *ProsCreateBulk) Exec(ctx context.Context) error {
	_, err := pcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pcb *ProsCreateBulk) ExecX(ctx context.Context) {
	if err := pcb.Exec(ctx); err != nil {
		panic(err)
	}
}
