// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/hossein1376/kala/internal/ent/brand"
	"github.com/hossein1376/kala/internal/ent/category"
	"github.com/hossein1376/kala/internal/ent/image"
	"github.com/hossein1376/kala/internal/ent/order"
	"github.com/hossein1376/kala/internal/ent/product"
	"github.com/hossein1376/kala/internal/ent/schema"
	"github.com/hossein1376/kala/internal/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	brandMixin := schema.Brand{}.Mixin()
	brandMixinFields0 := brandMixin[0].Fields()
	_ = brandMixinFields0
	brandFields := schema.Brand{}.Fields()
	_ = brandFields
	// brandDescCreateTime is the schema descriptor for create_time field.
	brandDescCreateTime := brandMixinFields0[0].Descriptor()
	// brand.DefaultCreateTime holds the default value on creation for the create_time field.
	brand.DefaultCreateTime = brandDescCreateTime.Default.(func() time.Time)
	// brandDescUpdateTime is the schema descriptor for update_time field.
	brandDescUpdateTime := brandMixinFields0[1].Descriptor()
	// brand.DefaultUpdateTime holds the default value on creation for the update_time field.
	brand.DefaultUpdateTime = brandDescUpdateTime.Default.(func() time.Time)
	// brand.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	brand.UpdateDefaultUpdateTime = brandDescUpdateTime.UpdateDefault.(func() time.Time)
	categoryMixin := schema.Category{}.Mixin()
	categoryMixinFields0 := categoryMixin[0].Fields()
	_ = categoryMixinFields0
	categoryFields := schema.Category{}.Fields()
	_ = categoryFields
	// categoryDescCreateTime is the schema descriptor for create_time field.
	categoryDescCreateTime := categoryMixinFields0[0].Descriptor()
	// category.DefaultCreateTime holds the default value on creation for the create_time field.
	category.DefaultCreateTime = categoryDescCreateTime.Default.(func() time.Time)
	// categoryDescUpdateTime is the schema descriptor for update_time field.
	categoryDescUpdateTime := categoryMixinFields0[1].Descriptor()
	// category.DefaultUpdateTime holds the default value on creation for the update_time field.
	category.DefaultUpdateTime = categoryDescUpdateTime.Default.(func() time.Time)
	// category.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	category.UpdateDefaultUpdateTime = categoryDescUpdateTime.UpdateDefault.(func() time.Time)
	// categoryDescName is the schema descriptor for name field.
	categoryDescName := categoryFields[0].Descriptor()
	// category.NameValidator is a validator for the "name" field. It is called by the builders before save.
	category.NameValidator = categoryDescName.Validators[0].(func(string) error)
	// categoryDescDescription is the schema descriptor for description field.
	categoryDescDescription := categoryFields[1].Descriptor()
	// category.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	category.DescriptionValidator = categoryDescDescription.Validators[0].(func(string) error)
	imageFields := schema.Image{}.Fields()
	_ = imageFields
	// imageDescName is the schema descriptor for name field.
	imageDescName := imageFields[0].Descriptor()
	// image.NameValidator is a validator for the "name" field. It is called by the builders before save.
	image.NameValidator = imageDescName.Validators[0].(func(string) error)
	// imageDescPath is the schema descriptor for path field.
	imageDescPath := imageFields[1].Descriptor()
	// image.PathValidator is a validator for the "path" field. It is called by the builders before save.
	image.PathValidator = imageDescPath.Validators[0].(func(string) error)
	// imageDescWidth is the schema descriptor for width field.
	imageDescWidth := imageFields[3].Descriptor()
	// image.WidthValidator is a validator for the "width" field. It is called by the builders before save.
	image.WidthValidator = imageDescWidth.Validators[0].(func(int32) error)
	// imageDescHeight is the schema descriptor for height field.
	imageDescHeight := imageFields[4].Descriptor()
	// image.HeightValidator is a validator for the "height" field. It is called by the builders before save.
	image.HeightValidator = imageDescHeight.Validators[0].(func(int32) error)
	// imageDescSizeKB is the schema descriptor for size_kb field.
	imageDescSizeKB := imageFields[5].Descriptor()
	// image.SizeKBValidator is a validator for the "size_kb" field. It is called by the builders before save.
	image.SizeKBValidator = imageDescSizeKB.Validators[0].(func(float64) error)
	orderMixin := schema.Order{}.Mixin()
	orderMixinFields0 := orderMixin[0].Fields()
	_ = orderMixinFields0
	orderFields := schema.Order{}.Fields()
	_ = orderFields
	// orderDescCreateTime is the schema descriptor for create_time field.
	orderDescCreateTime := orderMixinFields0[0].Descriptor()
	// order.DefaultCreateTime holds the default value on creation for the create_time field.
	order.DefaultCreateTime = orderDescCreateTime.Default.(func() time.Time)
	// orderDescUpdateTime is the schema descriptor for update_time field.
	orderDescUpdateTime := orderMixinFields0[1].Descriptor()
	// order.DefaultUpdateTime holds the default value on creation for the update_time field.
	order.DefaultUpdateTime = orderDescUpdateTime.Default.(func() time.Time)
	// order.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	order.UpdateDefaultUpdateTime = orderDescUpdateTime.UpdateDefault.(func() time.Time)
	productMixin := schema.Product{}.Mixin()
	productMixinFields0 := productMixin[0].Fields()
	_ = productMixinFields0
	productFields := schema.Product{}.Fields()
	_ = productFields
	// productDescCreateTime is the schema descriptor for create_time field.
	productDescCreateTime := productMixinFields0[0].Descriptor()
	// product.DefaultCreateTime holds the default value on creation for the create_time field.
	product.DefaultCreateTime = productDescCreateTime.Default.(func() time.Time)
	// productDescUpdateTime is the schema descriptor for update_time field.
	productDescUpdateTime := productMixinFields0[1].Descriptor()
	// product.DefaultUpdateTime holds the default value on creation for the update_time field.
	product.DefaultUpdateTime = productDescUpdateTime.Default.(func() time.Time)
	// product.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	product.UpdateDefaultUpdateTime = productDescUpdateTime.UpdateDefault.(func() time.Time)
	// productDescName is the schema descriptor for name field.
	productDescName := productFields[0].Descriptor()
	// product.NameValidator is a validator for the "name" field. It is called by the builders before save.
	product.NameValidator = productDescName.Validators[0].(func(string) error)
	// productDescDescription is the schema descriptor for description field.
	productDescDescription := productFields[1].Descriptor()
	// product.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	product.DescriptionValidator = productDescDescription.Validators[0].(func(string) error)
	// productDescRating is the schema descriptor for rating field.
	productDescRating := productFields[3].Descriptor()
	// product.RatingValidator is a validator for the "rating" field. It is called by the builders before save.
	product.RatingValidator = productDescRating.Validators[0].(func(float64) error)
	// productDescRatingCount is the schema descriptor for rating_count field.
	productDescRatingCount := productFields[4].Descriptor()
	// product.RatingCountValidator is a validator for the "rating_count" field. It is called by the builders before save.
	product.RatingCountValidator = productDescRatingCount.Validators[0].(func(int32) error)
	// productDescPrice is the schema descriptor for price field.
	productDescPrice := productFields[5].Descriptor()
	// product.PriceValidator is a validator for the "price" field. It is called by the builders before save.
	product.PriceValidator = productDescPrice.Validators[0].(func(int32) error)
	// productDescQuantity is the schema descriptor for quantity field.
	productDescQuantity := productFields[6].Descriptor()
	// product.QuantityValidator is a validator for the "quantity" field. It is called by the builders before save.
	product.QuantityValidator = productDescQuantity.Validators[0].(func(int32) error)
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreateTime is the schema descriptor for create_time field.
	userDescCreateTime := userMixinFields0[0].Descriptor()
	// user.DefaultCreateTime holds the default value on creation for the create_time field.
	user.DefaultCreateTime = userDescCreateTime.Default.(func() time.Time)
	// userDescUpdateTime is the schema descriptor for update_time field.
	userDescUpdateTime := userMixinFields0[1].Descriptor()
	// user.DefaultUpdateTime holds the default value on creation for the update_time field.
	user.DefaultUpdateTime = userDescUpdateTime.Default.(func() time.Time)
	// user.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	user.UpdateDefaultUpdateTime = userDescUpdateTime.UpdateDefault.(func() time.Time)
	// userDescStatus is the schema descriptor for status field.
	userDescStatus := userFields[7].Descriptor()
	// user.DefaultStatus holds the default value on creation for the status field.
	user.DefaultStatus = userDescStatus.Default.(bool)
}
