// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"kala/internal/ent/predicate"
	"kala/internal/ent/subcategory"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SubCategoryDelete is the builder for deleting a SubCategory entity.
type SubCategoryDelete struct {
	config
	hooks    []Hook
	mutation *SubCategoryMutation
}

// Where appends a list predicates to the SubCategoryDelete builder.
func (scd *SubCategoryDelete) Where(ps ...predicate.SubCategory) *SubCategoryDelete {
	scd.mutation.Where(ps...)
	return scd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (scd *SubCategoryDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, scd.sqlExec, scd.mutation, scd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (scd *SubCategoryDelete) ExecX(ctx context.Context) int {
	n, err := scd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (scd *SubCategoryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(subcategory.Table, sqlgraph.NewFieldSpec(subcategory.FieldID, field.TypeInt))
	if ps := scd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, scd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	scd.mutation.done = true
	return affected, err
}

// SubCategoryDeleteOne is the builder for deleting a single SubCategory entity.
type SubCategoryDeleteOne struct {
	scd *SubCategoryDelete
}

// Where appends a list predicates to the SubCategoryDelete builder.
func (scdo *SubCategoryDeleteOne) Where(ps ...predicate.SubCategory) *SubCategoryDeleteOne {
	scdo.scd.mutation.Where(ps...)
	return scdo
}

// Exec executes the deletion query.
func (scdo *SubCategoryDeleteOne) Exec(ctx context.Context) error {
	n, err := scdo.scd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{subcategory.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (scdo *SubCategoryDeleteOne) ExecX(ctx context.Context) {
	if err := scdo.Exec(ctx); err != nil {
		panic(err)
	}
}
